
<?php

$title = $this->translate('Mon Profil');
# meta keywords
$this->headMeta()->appendName('keywords', 'Profile');
# meta description
$this->headMeta()->appendName('profile', 'profile ');
# page title
$this->headTitle($this->escapeHtml($title));

$form = $this->form;
$form->setAttribute('action', $this->url('profile'));
$form->prepare();

?>


<div class="widget-box">
    <div class="widget-title"><h5>Mon profil</h5></div> 
    <div class="container">  

            <h3 class="mb-3 pt-2 text-md-center">
				<?= $this->escapeHtml($this->translate('Mon profil')); ?>
			</h3>

			<?= $this->form()->openTag($form); ?>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-ad"></i></span>
                        <?= $this->formText($form->get('nom')); ?> 
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="nom" >?</button>
                    </div>   
                </div>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-ad"></i></span>
                        <?= $this->formText($form->get('prenom')); ?> 
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="prenom" >?</button>
                    </div>   
                </div>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-globe-africa"></i></span>
                        <?= $this->formSelect($form->get('nationaliter')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="nationaliter" >?</button>
                    </div>   
                </div>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-birthday-cake"></i></span>
                        <?= $this->formDateSelect($form->get('birthday')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="birthday" >?</button>
                    </div>   
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-street-view"></i></span>
                        <?= $this->formText($form->get('lieudenaissance')); ?> 
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="lieudenaissance" >?</button>
                    </div>   
                </div>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-venus-mars"></i></span>
                        <?= $this->formSelect($form->get('gender')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="gender" >?</button>
                    </div>   
                </div>
                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-map"></i></span>
                        <?= $this->formTextarea($form->get('adress')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="adress" >?</button>
                    </div>   
                </div>

                <hr>
                <div class="row"> 
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-mobile-alt"></i></span>
                        <?= $this->formText($form->get('tel1')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="tel" >?</button>
                    </div>   
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-phone-alt"></i></span>
                        <?= $this->formText($form->get('tel2')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="tel" >?</button>
                    </div>   
                    <div class="input-group flex-nowrap col">
                        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-tty"></i></span>
                        <?= $this->formText($form->get('tel3')); ?>
                        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="tel" >?</button>
                    </div>   
                </div>
                
            <!-- submit and csrf fields -->
			<div class="mb-3 float-right">
                <?= $this->formHidden($form->get('csrf')); ?>
                <div class="text-danger">
                	<?= $this->formElementErrors($form->get('csrf')); ?>
                </div>
				<hr>
                <?= $this->formSubmit($form->get('enregistrer')); ?>           
			</div>	

			<!-- close the form -->
			<?= $this->form()->closeTag(); ?>

    </div>
</div>