<?php

$title =  $this->translate('Contextes'); # page title
# meta keywords
$this->headMeta()->appendName('keywords', 'Definition contexte,  Contexte');
# meta description
$this->headMeta()->appendName('description', 'Ajout/mise a jour de Contexte');
# page title
$this->headTitle($this->escapeHtml($title));


#form
$form = $this->form;
$form->setAttribute('action', $this->url('contexte/actions-contexte-structure-save',['id',$this->id]));  #oops
$form->prepare();

?> 
 <script src="<?=$this->basePath()?>/jslib/formbuilder/form-builder.min.js"></script> 

 
	 
 
<div class="card card-primary">
	<div class="card-header">
	<h3 class="card-title">Ajouter contexte</h3>
	</div>
	<div class="card-body"> 
  
	<div id="message_contexte"></div>
	<?= $this->form()->openTag($form); ?> 
    <?= $this->formSubmit($form->get('create')); ?>
    <!-- add the module input field -->
    <div class="mb-3">
        <?php $this->formLabel($form->get('idmetaetapepreinscription')); ?>
        <div class="form-group">
            <?= $this->formText($form->get('idmetaetapepreinscription')); ?> 
        </div> 
        <div class="text-danger"> 
                <?= $this->formElementErrors($form->get('idmetaetapepreinscription')); ?>  
        </div>
    </div>	
    <div class="mb-3">
        <?php $this->formLabel($form->get('labelmataetape')); ?>
        <div class="form-group">
            <?= $this->formText($form->get('labelmataetape')); ?> 
        </div> 
        <div class="text-danger"> 
                <?= $this->formElementErrors($form->get('labelmataetape')); ?>  
        </div>
    </div>	
 


    <div class="mb-3">
            <?php $this->formLabel($form->get('idcontexte')); ?>
        <div class="form-group">
            <?= $this->formSelect($form->get('idcontexte')); ?>
        </div>
        
        <div class="text-danger">
            <?= $this->formElementErrors($form->get('idcontexte')); ?>
        </div>
    </div>
    <div class="mb-3">
            <?php $this->formLabel($form->get('idcontextemetaetape')); ?>
        <div class="form-group">
            <?= $this->formSelect($form->get('idcontextemetaetape')); ?>
        </div>
        
        <div class="text-danger">
            <?= $this->formElementErrors($form->get('idcontextemetaetape')); ?>
        </div>
    </div>


    <div class="mb-3">
        <?php $this->formLabel($form->get('labelmetaorder')); ?>
        <div class="form-group">
            <?= $this->formText($form->get('labelmetaorder')); ?> 
        </div> 
        <div class="text-danger"> 
                <?= $this->formElementErrors($form->get('labelmetaorder')); ?>  
        </div>
    </div>	
 
   
    <div class="custom-control custom-checkbox">
        <?=$this->formCheckbox($form->get('obligatoire')); ?>
        <?= $this->formLabel($form->get('obligatoire')); ?>
    </div> 
    
    <div class="mb-3">
        <?= $this->formLabel($form->get('contenuspecific')); ?>
        <div class="input-group">
            <?= $this->formTextarea($form->get('contenuspecific')); ?>
        </div>

        <div class="text-danger">
            <?= $this->formElementErrors($form->get('contenuspecific')); ?>
        </div> 
    </div>



    <div class="mb-3">
        <?= $this->formLabel($form->get('descreptionmetaetape')); ?>
        <div class="input-group">
            <?= $this->formTextarea($form->get('descreptionmetaetape')); ?>
        </div>

        <div class="text-danger">
            <?= $this->formElementErrors($form->get('descreptionmetaetape')); ?>
        </div> 
    </div>
	<!-- submit button -->
	<div class="mb-3 float-right">  
		<?= $this->formHidden($form->get('csrf')); ?>
		<div class="text-danger">
			<?= $this->formElementErrors($form->get('csrf')); ?>
		</div>
	
	</div> 
  <div id="fb-editor"></div>
  

	<?= $this->form()->closeTag(); ?>
  
 </div>
 </div>