<script>  
    $(function(){

        $('[data-toggle="tabajax-2"]').click(function(e) {
        var $this = $(this),
            loadurl = $this.attr('href'),
            targ = $this.attr('data-target');
            $("#"+targ).html('<div class="overlay dark"><i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Chargement...</div></div>'); 
          $.get(loadurl, function(data) {
              $("#"+targ).html(data);
          });

        $this.tab('show');
        return false;
      });
      $('[data-toggle="tabajax"]:first').click();

      

    
  });

</script>

<div class="col-md-12">
  <div class="card card-primary card-tabs">
    <div class="card-header p-0 pt-1">
      <ul class="nav nav-tabs" id="custom-tabs-five-tab" role="tablist"> 
        <li class="nav-item">
          <a   class="nav-link" data-target="content-tabs-2" id="custom-tabs-five-overlay-tab" data-toggle="tabajax-2" href="<?=$this->url('etapes/actions-session-Meta-etape-contexte-add',['categorie'=>$this->categorie_id,'id'=>$this->id])?>" role="tab" aria-controls="custom-tabs-five-overlay" aria-selected="true">Modifier les Contextes d'etapes Standard</a>
        </li> 
        <li class="nav-item">
          <a   class="nav-link" data-target="content-tabs-2" id="custom-tabs-five-overlay-tab" data-toggle="tabajax-2" href="<?=$this->url('etapes/actions-session-Meta-etape-contexte-lister',['metacontexte'=>$this->id])?>" role="tab" aria-controls="custom-tabs-five-overlay" aria-selected="true">Liste les etapes Standard</a>
        </li>
        <li class="nav-item">
          <a   class="nav-link" data-target="content-tabs-2" id="custom-tabs-five-overlay-tab" data-toggle="tabajax-2" href="<?=$this->url('etapes/actions-session-Metat-etape-add',['metacontexte'=>$this->id])?>" role="tab" aria-controls="custom-tabs-five-overlay" aria-selected="true">Ajouter une etape Standard</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content" id="content-tabs-2">
         
      </div>
    </div>
    <!-- /.card -->
  </div>
</div> 