
<div class="row"> 
    <div class="input-group col">
        <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fa fa-graduation-cap"></i></span>
        <label class="input-group-text d-sm-none d-md-block" for="inputGroupSelect01">Cycle</label>
        <select class="form-select" id="inputGroupSelect01" aria-describedby="inputGroupSelect01" >
            <option selected>Cycle...</option> 
            <option value="Premier">Premier cycle (Licence,Technicien Supérieur,Metrise)</option> 
            <option value="Preparatoire">Cycle préparatoire</option> 
        </select>
        <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect01" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Type de diplôme Licence/Master/Ingénieur...">?</button>
    </div>
</div>
<hr>
<div class="row"> 

    <div class="col-md-12">  

        <div class="row"> 
            <div class="input-group col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fa fa-graduation-cap"></i></span>
                <label class="input-group-text d-sm-none d-md-block" for="inputGroupSelect01">Type de diplôme</label>
                <select class="form-select" id="inputGroupSelect01" aria-describedby="inputGroupSelect01" >
                    <option selected>Type de diplôme...</option> 
                </select>
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect01" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Type de diplôme Licence/Master/Ingénieur...">?</button>
            </div>
            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-user-graduate"></i></span>
                <input type="text" class="form-control" placeholder="Diplôme" name="titrediplome" aria-label="titre diplome" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="titrediplome" >?</button>
            </div>  
            
            <div class="input-group col">
            <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-award"></i></span>
                <label class="input-group-text d-sm-none d-md-block" for="inputGroupSelect02">Spécialité</label>
                <select class="form-select" id="inputGroupSelect02">
                    <option selected>Spécialité...</option> 
                </select>
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect02" >?</button>
            </div> 
            
        </div>

        <hr>
        <div class="row"> 
        
            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-school"></i></span>
                <input type="text" name="etablissement" class="form-control" placeholder="Etablissement*" aria-label="Username" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="etablissement" >?</button>
            </div> 

            <div class="input-group col">
                <span class="input-group-text d-sm-none d-md-block" id="inputGroupSelect03"><i class="far fa-calendar-alt"></i></span> 
                <select class="form-select" id="inputGroupSelect03">
                    <option selected> Année d'obtention...</option> 
                </select>
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect03" >?</button>
            </div> 
           
            <div class="input-group col">
            <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-globe-americas"></i></span>
                <label class="input-group-text d-sm-none d-md-block" for="inputGroupSelect04">Pays</label>
                <select class="form-select" id="inputGroupSelect04">
                    <option selected>Pays...</option> 
                </select>
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect04" >?</button>
            </div> 
         </div> 
         <hr>
        <div class="row"> 
            <div class="input-group col">
            <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-glasses"></i></span>
                <label class="input-group-text d-sm-none d-md-block" for="inputGroupSelect05"> Session et mention</label>
                <select class="form-select" id="inputGroupSelect05">
                    <option selected> Session et mention...</option> 
                </select>
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="inputGroupSelect05" >?</button>
            </div> 

            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fab fa-creative-commons-nd"></i></span>
                <input type="text" class="form-control" placeholder="Moyenne*" name="Moyenne" aria-label="Moyenne" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="Moyenne" >?</button>
            </div> 

            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-file-alt"></i></span>
                <input type="file" class="form-control" placeholder="Diplôme*" name="diplome" aria-label="diplome" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="diplome" >?</button>
            </div>
        </div>
        <hr>
        <div class="row"> 
            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-pray"></i></span>
                <input type="text" name="nbrreuisitecontrole" id="nbrreuisitecontrole" class="form-control" placeholder=" Combien de fois avez-vous été en session de rattrapage pendant ce cursus ?" aria-label="" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button"id="nbrreuisitecontrole" >?</button>
            </div>   
        </div>
        <hr>
        <div class="row"> 
            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-retweet"></i></span>
                <input type="text" class="form-control" placeholder=" Nombre d’années de redoublement"  name="nbrredouble"  id="nbrredouble" aria-label="redoublement" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="nbrredouble" >?</button>
            </div> 
            <div class="input-group flex-nowrap col">
                <span class="input-group-text d-sm-none d-md-block" id="addon-wrapping"><i class="fas fa-hospital-user"></i></span>
                <input type="text" class="form-control" placeholder="Nombre de fois de retrait d’inscription justifié" id="nbrretraiinscription" name="nbrretraiinscription" aria-label="" aria-describedby="addon-wrapping">
                <button class="btn btn2 btn-outline-secondary btn-info d-sm-none d-md-block" type="button" id="nbrretraiinscription" >?</button>
            </div> 

        </div>     
    </div>
     
</div>
<hr>
<div class="row">
    <div class="col">
    <?=$this->annee_etude?>
    </div>
</div>