
<div class="row">

    <div class="col-md-7"> 
                    <div class="row" style="margin-left:0px;--bs-gutter-x: 0rem;">                    
                    <div class="col-md-4">
                        <div class="dash-unit" style="height:300px;" >
                            <img src="images/brian.jpg" alt="Brian Smith"style="width:100%;">
                            <h1>OUSSAMA LIMAM</h1>
                            <h4>Tunis, Kélibia.</h4>
                            <h6>Date Sep 05, 1982</h6>
                        </div> 
                    </div>
                        <div class="col-md-8">
                            <div class="block-unit" style="height:300px;">   
                            <div class="col-md-12">
                                    <h4>Mon CV</h4>
                            </div>
                            <div class="col-md-12" style="padding:20px; text-align:center;">  
                                <div class="row" style="background-color:#ffffff;  height:50px; text-align:center; padding:10px; padding-left:45px;">
                                <div class="col-md-4">
                                <div class="oneBox">Affichier CV</div>
                                </div> 
                                <div class="col-md-4">
                                <div class="oneBox">Editer CV</div>
                                </div> 
                                <div class="col-md-4">
                                <div class="oneBox">Editer photo</div>
                                </div>
                                    </div>
                                    
                            </div>	
                            <div class="col-md-12" >
                                    <h4>Taux de remplissage de CV</h4>
                                    <div class="meter">
                                        <span style="width:30%;"></span>
                                    </div>
                            </div>
                            
                            <div class="col-md-12" style="margin-top: 4%;position:relative;">
                                    
                                    <p><span class="badge badge-one">89</span> Contacts / <span class="badge badge-success">137</span> Likes 
                                    <span class="badge badge-info">$ 11.887</span> Earnings / <span class="badge badge-important">9</span> New Orders</p>
                            </div> 
                        </div>
                        </div> 
                </div>  
            </div>

            <div class = "col-md-5">
                <div class="metrouicss">
                    <button class="command-button modelhysun1"><p>Calendrier</p></button>
                    <button class="command-button modelhysun2"><p>Uvt News</p></button>
                    <button class="command-button modelhysun3"><p>Mes Inscription</p></button>
                    <button class="command-button modelhysun4"><p>Cours</p></button>
                </div>
                <div class="widget-box">
                    <div class="widget-title">
                        <h5><i class="halflings-icon font"></i><span class="break"></span>Mon profil</h5> 
                    </div>
                    <div class="widget-content"> 
                        
                    </div>
                </div>
            </div>
</div>

<div class="widget-box">
    <div class="widget-title"><h5>Mes Informations </h5></div> 
    <div class="container">  
        <div class="row">
        </div>
    </div>
</div>