<div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Liste des Categories</h3>
                
              </div>
              <!-- /.card-header -->
              <div class="card-body"> 
                <table class="table table-bordred">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Titre</th> 
                        <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->ListeCategorie as $Categorie):?>
                            <tr>
                            <td id='ressources_<?=$Categorie->getIdcontextecategorie()?>'><?=$Categorie->getIdcontextecategorie()?></td>
                            <td><?=$Categorie->getLabelcontextecategorie()?></td> 
                            <td><button type="button" onclick="deletedata('<?=$this->url('ressources/actions-ressources-delete',['id'=>$Categorie->getIdcontextecategorie()])?>','ressources_<?=$Categorie->getIdcontextecategorie()?>','<?=$this->url('ressources')?>','content_ajax')" class="btn btn-flat btn-danger"><i class="fas fa-trash-alt"></i></button></td>

                            </tr>

                        <?php endforeach;?>
                    </tbody>
                </table>
                <?= $this->paginationControl(
                    $this->ListeCategorie,
                    'sliding',         
                    'partial/paginator-ajax',
                    ['route' => 'ressources']
                );?>
        </div>
</div>