<?php

$title =  $this->translate('Contextes'); # page title
# meta keywords
$this->headMeta()->appendName('keywords', 'Definition contexte,  Contexte');
# meta description
$this->headMeta()->appendName('description', 'Ajout/mise a jour de Contexte');
# page title
$this->headTitle($this->escapeHtml($title));


#form
$form = $this->form;
$form->setAttribute('action', $this->url('contexte/actions-contexte-save',['id',$this->id]));  #oops
$form->prepare();

?>
 

<script type="text/javascript">
    $(document).ready(
        function(){

			AjaxFormAccessAjaxReload("new_contexte","message_contexte",'<?=$this->url('contexte/actions-contexte-save',['id',$this->id])?>',['id'=>$this->id],'content_ajax',true);
        }
    );
</script>

 
<div class="card card-primary">
	<div class="card-header">
	<h3 class="card-title">Ajouter contexte</h3>
	</div>
	<div class="card-body"> 
  
	<div id="message_contexte"></div>
	<?= $this->form()->openTag($form); ?> 
 
        <!-- add the module input field -->
        <div class="mb-3">
            <?php $this->formLabel($form->get('labelcontexte')); ?>
            <div class="form-group">
                <?= $this->formText($form->get('labelcontexte')); ?> 
            </div> 
            <div class="text-danger"> 
                    <?= $this->formElementErrors($form->get('labelcontexte')); ?>  
            </div>
        </div>	

       <!-- add the module input field -->
        <div class="mb-3">
            <?php $this->formLabel($form->get('context_module')); ?>
            <div class="form-group">
                <?= $this->formText($form->get('context_module')); ?> 
            </div> 
            <div class="text-danger"> 
                    <?= $this->formElementErrors($form->get('context_module')); ?>  
            </div>
        </div>	

         <!-- add the controller input field -->
         <div class="mb-3">
            <?php $this->formLabel($form->get('context_controller')); ?>
            <div class="form-group">
                <?= $this->formText($form->get('context_controller')); ?> 
            </div> 
            <div class="text-danger"> 
                    <?= $this->formElementErrors($form->get('context_controller')); ?>  
            </div>
        </div>

        <!-- add the action input field -->
        <div class="mb-3">
            <?php $this->formLabel($form->get('context_action')); ?>
            <div class="form-group">
                <?= $this->formText($form->get('context_action')); ?> 
            </div> 
            <div class="text-danger"> 
                    <?= $this->formElementErrors($form->get('context_action')); ?>  
            </div>
        </div>
 

     <!--   idaccessmode select field -->
    <div class="mb-3">
            <?php $this->formLabel($form->get('idcontextecategorie')); ?>
        <div class="form-group">
            <?= $this->formSelect($form->get('idcontextecategorie')); ?>
        </div>
        
        <div class="text-danger">
            <?= $this->formElementErrors($form->get('idcontextecategorie')); ?>
        </div>
    </div>
     <!--   resources_descrept text field -->
    <div class="mb-3">
				<?= $this->formLabel($form->get('desccontexte')); ?>
				<div class="input-group">
					<?= $this->formTextarea($form->get('desccontexte')); ?>
				</div>

				<div class="text-danger">
					<?= $this->formElementErrors($form->get('desccontexte')); ?>
				</div>

			</div>
	<!-- submit button -->
	<div class="mb-3 float-right">
    
    <?= $this->formHidden($form->get('idcontexte')); ?>
		<?= $this->formHidden($form->get('csrf')); ?>
		<div class="text-danger">
			<?= $this->formElementErrors($form->get('csrf')); ?>
		</div>
		<?= $this->formSubmit($form->get('create')); ?>
	</div>

	<?= $this->form()->closeTag(); ?>
  
 </div>
 </div>