 
<script type="text/javascript"> 


$(function(){ 


	$("#tree").fancytree({
	    source: {
	            url: "<?=$this->url("contexte/actions-contexte-tree")?>"
	    },
	    lazyload: function(e, data){
	 
	            data.result = $.ajax({
	                    url: "<?=$this->url("contexte/actions-contexte-tree")?>",
	                    dataType: "json"
	            });
	    },
	    click: function(event, data) { 

	    	var keydata=data.node.key;
				var keysplit=keydata.split("_");
                
  	//save in session the key of formation choisie
    var url="<?=$this->url("contexte/actions-categorie-lister")?> ";
        if(keysplit[0]=="Category"){
            url="<?=$this->url("contexte/action-contexte-menu")?>/"+keysplit[1];/**filter module/mode**/
        }else if(keysplit[0]=="Structure"){
            url="<?=$this->url("contexte/actions-contexte-structure-add")?>/"+keysplit[2]+"/"+keysplit[1];/**filter module**/
        } else if(keysplit[0]=="Contexte"){
            url="<?=$this->url("contexte/actions-contexte-menu-structure")?>/"+keysplit[1]; /**modifier**/
        } 
 

        $.ajax({
            type:"POST",
            url: url,
            data:{
                id:data.node.key 
            },
            beforeSend :function(){
                $('#content_ajax').html("Encours...");
            },
            success:function(response){
                $('#content_ajax').html(response);
            }
        });
             
		 	
             
    	}
	});
  
	});
 



</script>

<div class="row">
    <div class="col-md-3" id="tree"></div>
    <div class="col-md-9">
        <div class="row">
            <div class="col-md-12"> 
                    <nav class="navbar navbar-expand navbar-orange navbar-dark">
                      <!-- Left navbar links -->
                      <ul class="navbar-nav"> 
                      <a class="nav-link"  href="#" role="button"><i class="fas fa-bars"></i></a>
                        <li class="nav-item d-none d-sm-inline-block">
                          <a href="#" onclick="AjaxOneLoader('<?=$this->url('contexte/actions-categorie-add')?>','content_ajax')" class="nav-link">Ajouter categorie</a>
                        </li> 
                      </ul> 
                    </nav> 
            </div>
        </div>
<hr>
        <div class="row">
            <div class="col-md-12"  id="content_ajax"></div>
        </div>

    </div>
</div> 